// Mocks generated by Mockito 5.4.4 from annotations
// in products_app_demo/test/data/datasources/product_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:products_app_demo/data/datasources/product_service.dart' as _i3;
import 'package:products_app_demo/data/models/product_details_model.dart'
    as _i6;
import 'package:products_app_demo/data/models/product_list_model.dart' as _i5;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i3.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.ProductListModel?>> getProductList(
    int? limit,
    int? skip,
    List<String>? select,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductList,
          [
            limit,
            skip,
            select,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<_i5.ProductListModel?>>.value(
            _FakeHttpResponse_0<_i5.ProductListModel?>(
          this,
          Invocation.method(
            #getProductList,
            [
              limit,
              skip,
              select,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<_i5.ProductListModel?>>);

  @override
  _i4.Future<_i2.HttpResponse<_i6.ProductDetailsModel?>> getProduct(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.HttpResponse<_i6.ProductDetailsModel?>>.value(
                _FakeHttpResponse_0<_i6.ProductDetailsModel?>(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<_i6.ProductDetailsModel?>>);
}
